
version: 2
updates:

  # Update Python dependencies weekly.
  - package-ecosystem: "pip"
    directory: "/" # Read the root pyproject.toml.
    schedule:
      interval: "weekly"

    reviewers:
      - "patrickab"

    # Group Docker SDK updates to reduce review noise.
    groups:
      docker-sdk:
        patterns:
          - "docker*"
